#include <rtems/ramdisk.h>

#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER
#define CONFIGURE_APPLICATION_EXTRA_DRIVERS RAMDISK_DRIVER_TABLE_ENTRY

#define CONFIGURE_UNLIMITED_OBJECTS
#define CONFIGURE_UNIFIED_WORK_AREAS

#define CONFIGURE_RTEMS_INIT_TASKS_TABLE

/* filesystem */
#define CONFIGURE_FILESYSTEM_DOSFS
#define CONFIGURE_USE_IMFS_AS_BASE_FILESYSTEM
#define CONFIGURE_MAXIMUM_FILE_DESCRIPTORS 10
#define CONFIGURE_IMFS_MEMFILE_BYTES_PER_BLOCK 512

#define CONFIGURE_APPLICATION_NEEDS_LIBBLOCK

#define CONFIGURE_INIT
#include <rtems/confdefs.h>
